var races = [
  {
    'race': 'Argonier',
    'subraces': [
      {
        'name': 'Argonier',
        'male': 'assets/argonian/male.jpg',
        'female': 'assets/argonian/female.jpg',
        'size': '1,73 - 1,81 Meter',
        'weight': 'bis zu 85 KG',
        'maxAge': '~70 Jahre',
        'description': 'Die Argonier sind echsenartige, jedoch humanoide Wesen. Sie können unter Wasser atmen und sind immun gegen Krankheiten und viele Gifte.\nSie sind flink im Wasser und unebenen Gebieten und Experten in Sachen Natur und Kräuter. Sie sind schlau und flink, werden alelrdings von manch anderen Rassen wegen ihres aussehens verachtet.',
        'racials': ['+Wasseratmung', '+Krankheitsimmunität', '-Hitzeempfindlich', '+Giftresistenz',],
      },
    ],
  },
  {
    'race': 'Elfen',
    'subraces': [
      {
        'name': 'Elf(e)',
        'male': 'assets/elves/male.jpg',
        'female': 'assets/elves/female.jpg',
        'size': '1,70 - 1,90 Meter',
        'weight': 'bis zu 42 KG',
        'maxAge': '~550 Jahre',
        'description': 'Rasse der Elfen',
        'racials': ['1', '2', '3'],
      },
      {
        'name': 'Dunkel- Elf(e)',
        'male': 'assets/elves/dark_male.jpg',
        'female': 'assets/elves/dark_female.jpg',
        'size': '1,75 - 1,90 Meter',
        'weight': 'bis zu 45 KG',
        'maxAge': '~500 Jahre',
        'description': 'Rasse der Dunkel- Elfen',
        'racials': ['1', '2', '3'],
      },
    ],
  },
  {
    'race': 'Gnom',
    'subraces': [
      {
        'name': 'Gnome',
        'male': 'assets/gnome/male.jpg',
        'female': 'assets/gnome/female.jpg',
        'size': '1,0 - 1,1 Meter',
        'weight': 'bis zu 50 KG',
        'maxAge': '~200',
        'description': 'Rasse der Gnome',
        'racials': ['1', '2', '3'],
      },
    ],
  },
  {
    'race': 'Menschen',
    'subraces': [
      {
        'name': 'Mensch',
        'male': 'assets/humans/male.jpg',
        'female': 'assets/humans/female.jpg',
        'size': '1,60 - 1,90 Meter',
        'weight': 'bis zu 110 KG',
        'maxAge': '~80 Jahre',
        'description': 'Die Menschen sind die anpassungsstärkste und ambitionierteste Rasse. Die haben eine kleinere Lebensspanne und sind keine magischen Wesen, was sie aber durch ihre Willensstärke und Durchsetzungsfähigkeit keineswegs schwächer machen.\nMenschen sind meist Teamplayer, Abenteurer und ziehen alles durch, was sie angefangen haben.',
        'racials': ['1', '2', '3'],
      },
      {
        'name': 'Gesetzlose(r)',
        'male': 'assets/humans/outlaw_male.jpg',
        'female': 'assets/humans/outlaw_female.jpg',
        'size': '1,60 - 1,90 Meter',
        'weight': 'bis zu 110 KG',
        'maxAge': '~80 Jahre',
        'description': '',
        'racials': ['1', '2', '3'],
      },
    ],
  },
  {
    'race': 'Ork',
    'subraces': [
      {
        'name': 'Ork',
        'male': 'assets/orc/male.jpg',
        'female': 'assets/orc/female.jpg',
        'size': '1,85 - 2,05 Meter',
        'weight': 'bis zu 130 KG',
        'maxAge': '~60 Jahre',
        'description': 'Die Orks sind reine Krieger, die das Kämpfen lieben. Sie sind sehr schmerzresistent und auch wenn sie viele für brutale Mörder halten eher auf ebenbürtige Kämpfe aus, anstatt sich an Hilflosen zu vergehen.\nStärke und ausdauer prägen sie, als auch der Umgang mit Zweihandwaffen.',
        'racials': ['1', '2', '3'],
      },
    ],
  },
  {
    'race': 'Tiefling',
    'subraces': [
      {
        'name': 'Tiefling',
        'male': 'assets/tiefling/male.jpg',
        'female': 'assets/tiefling/female.jpg',
        'size': '1,78 - 2,05 Meter',
        'weight': 'bis zu 105 KG',
        'maxAge': '~100 Jahre',
        'description': 'Tieflinge sind halb Mensch, halb Dämon. Sie sind nicht von Natur aus böse, jedoch werden sie wegen ihres aussehens und ihrer magischen Kräfte oft für böse gehalten.\nSie sind immun gegen viele statusverändernde Magie und können auf kurze Sicht im dunkeln sehen. Sie sind extrem Stark, haben aber dafür nicht so starke Ausdauer.',
        'racials': ['1', '2', '3'],
      },
    ],
  },
  {
    'race': 'Zwerge',
    'subraces': [
      {
        'name': 'Zwerg',
        'male': 'assets/dwarfs/male.jpg',
        'female': 'assets/dwarfs/female.jpg',
        'size': '1,0 - 1,2 Meter',
        'weight': 'bis zu 70 KG',
        'maxAge': '~250 Jahre',
        'description': 'Zwerge sind kühn und robust. Sie sind als talentierte und furchtlose Krieger, exzellente Bergbauer, sowie für ihre Metallverarbeitung und Handwerkskunst bekannt.\nZwerge sind zwar nicht die schnellsten, besitzen dafür aber eine starke AUsdauer. Zwerge sind klug und haben ein großes Interesse an wirtschaftlichem Fortschritt.',
        'racials': ['1', '2', '3'],
      },
      {
        'name': 'Berg- Zwerg',
        'male': 'assets/dwarfs/mountain_male.jpg',
        'female': 'assets/dwarfs/mountain_female.jpg',
        'size': '1,0 - 1,1 Meter',
        'weight': 'bis zu 68 KG',
        'maxAge': '~270 Jahre',
        'description': 'Zwerge sind kühn und robust. Sie sind als talentierte und furchtlose Krieger, exzellente Bergbauer, sowie für ihre Metallverarbeitung und Handwerkskunst bekannt.\nAls ein Berg- Zwerg bist du stark und wiederstandsfähig. Raues Wetter, sowie Kälte und Nässe macht dir nichts aus. Berg-Zwerge sind zu dem extremst ausdauernd und haben ein sehr starkes Durchhaltevermögen.',
        'racials': ['1', '2', '3'],
      },
      {
        'name': 'Dunkel- Zwerg',
        'male': 'assets/dwarfs/dark_male.jpg',
        'female': 'assets/dwarfs/dark_female.jpg',
        'size': '1,0 - 1,2 Meter',
        'weight': 'bis zu 71 KG',
        'maxAge': '~300 Jahre',
        'description': 'Zwerge sind kühn und robust. Sie sind als talentierte und furchtlose Krieger, exzellente Bergbauer, sowie für ihre Metallverarbeitung und Handwerkskunst bekannt.\nDunkel- Zwerge haben geschärfte Sinne, starke Intuition und die größte Wiedderstandskraft von allen Zwergen - eine wahre Kämpfernatur.',
        'racials': ['1', '2', '3'],
      },
    ],
  },
];
